#to deploy the build images from the ci steps
#when ci workflow is complted
name: cd

on:
  workflow_run:
    workflows: ["lint"]
    types: 
      - completed
    
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true


      - name: Deploy to server
        run: |
          echo "Deploying build images to the server..."
          docker pull ughate/simple-backend:latest
          docker pull ughate/simple-frontend:latest
          docker run -d --name ughate/simple-backend -p 8080:8080 ughate/simple-backend:latest
          docker run -d --name ughate/simple-frontend -p 3000:3000 ughate/simple-frontend:latest

          # Add your deployment commands here
