#name of workflow
name: Build and Push to Docker Hub 
#when the workflow should be triggered
on:
  push:
    branches: [ "main" ]
#what jobs will be run upon the workflow trigger
jobs:
  # to lint the code
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v7

    # Run Frontend HTML Linter
    - name: Run HTML Hint
      run: |
        npm install -g htmlhint
        htmlhint "frontend/**/*.html"

    # Run Backend JavaScript Linter
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: backend/package.json
   
    - name: Install backend development tools
      run: |
        npm install --package-lock-only
        npm ci

    - name: Run ESLint
      run: |
        cd backend
        npm run lint
        
  build-and-push:
    needs: lint #lint should be successfull to build
    runs-on: ubuntu-latest
#steps inside jobs
    #This steps copy the code to ephermal runner for review syntax by linter in step 2
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v7

    - name: Log in to Docker Hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Build and push Frontend
      uses: docker/build-push-action@v7
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/simple-frontend:latest

    - name: Build and push Backend
      uses: docker/build-push-action@v7
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/simple-backend:latest
